from pathlib import Path


def create_godot_project_file(project_dir: Path, project_name: str) -> Path:
    p = project_dir / "project.godot"
    p.write_text(
        f"""; Engine configuration file.\n; Generated by AI Game Development Agent.\n\nconfig_version=5\n\n[application]\nconfig/name=\"{project_name}\"\nrun/main_scene=\"res://scenes/Main.tscn\"\nconfig/features=PackedStringArray(\"4.2\")\n""",
        encoding="utf-8",
    )
    return p


def create_default_folders(project_dir: Path) -> list[Path]:
    dirs = [
        "scenes", "scripts", "docs", "assets/art/concepts", "assets/art/sprites", "assets/art/ui", "assets/art/icons",
        "assets/audio/bgm", "assets/audio/sfx", "assets/models", "assets/generated/cache/images", "assets/generated/cache/audio", "assets/generated/cache/models"
    ]
    out = []
    for d in dirs:
        p = project_dir / d
        p.mkdir(parents=True, exist_ok=True)
        out.append(p)
    return out


def create_basic_scenes(project_dir: Path) -> list[Path]:
    names = ["Main.tscn", "Player.tscn", "Enemy.tscn", "UI.tscn"]
    out=[]
    for n in names:
        p = project_dir / "scenes" / n
        p.write_text("[gd_scene format=3]\n", encoding="utf-8")
        out.append(p)
    return out


def create_basic_scripts(project_dir: Path) -> list[Path]:
    scripts = {
        "Player.gd": "extends CharacterBody2D\nfunc _physics_process(delta):\n\tvar dir=Input.get_vector('move_left','move_right','move_up','move_down')\n\tvelocity=dir*200\n\tmove_and_slide()\n",
        "Enemy.gd": "extends CharacterBody2D\nfunc _physics_process(delta):\n\tpass\n",
        "GameManager.gd": "extends Node\nvar state='playing'\n",
        "UIController.gd": "extends CanvasLayer\nfunc update_status(text):\n\tpass\n",
    }
    out=[]
    for n,c in scripts.items():
        p=project_dir/"scripts"/n
        p.write_text(c, encoding="utf-8")
        out.append(p)
    return out
